/**
    * id (number)
    * title (string)
    * company (string)
    * location (string)
    * type ('full-time' | 'part-time' | 'remote' | 'contract')
    * category ('frontend' | 'backend' | 'fullstack' | 'design' | 'devops')
    * salary (string) → "₹8-12 LPA"
    * experience (string) → "2-4 years"
    * description (string)
    * requirements (array of strings)
    * postedDate (string) → "2026-05-01"
    * logo (emoji) → "⚛️"
    * featured (boolean)
**/

export const jobs = [
    {
        id: 1,
        title: "Senior React Native Developer",
        company: "Razorpay",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "frontend",
        salary: "₹18-25 LPA",
        experience: "4-6 years",
        description: "Build and maintain high-performance mobile applications used by millions of merchants across India.",
        requirements: ["4+ years React Native", "TypeScript", "Redux", "REST APIs", "Git"],
        postedDate: "2026-05-01",
        logo: "💳",
        featured: true,
    },
    {
        id: 2,
        title: "Backend Engineer",
        company: "Zepto",
        location: "Mumbai, Maharashtra",
        type: "full-time",
        category: "backend",
        salary: "₹15-22 LPA",
        experience: "3-5 years",
        description: "Design and build scalable backend services for India's fastest growing quick commerce platform.",
        requirements: ["Node.js", "Express.js", "MongoDB", "Redis", "Docker"],
        postedDate: "2026-05-02",
        logo: "⚡",
        featured: true,
    },
    {
        id: 3,
        title: "Frontend Developer",
        company: "CRED",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "frontend",
        salary: "₹12-18 LPA",
        experience: "2-4 years",
        description: "Create beautiful and performant web experiences for India's most design-conscious fintech company.",
        requirements: ["React.js", "TypeScript", "Tailwind CSS", "GraphQL", "Jest"],
        postedDate: "2026-05-01",
        logo: "🏆",
        featured: true,
    },
    {
        id: 4,
        title: "Full Stack Developer",
        company: "Swiggy",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "fullstack",
        salary: "₹14-20 LPA",
        experience: "3-5 years",
        description: "Work on full stack features for India's leading food delivery platform serving 500+ cities.",
        requirements: ["React.js", "Node.js", "MongoDB", "AWS", "Microservices"],
        postedDate: "2026-04-28",
        logo: "🍔",
        featured: false,
    },
    {
        id: 5,
        title: "UI/UX Designer",
        company: "Zomato",
        location: "Gurugram, Haryana",
        type: "full-time",
        category: "design",
        salary: "₹10-15 LPA",
        experience: "2-4 years",
        description: "Design intuitive user experiences for food discovery and delivery across web and mobile platforms.",
        requirements: ["Figma", "User Research", "Prototyping", "Design Systems", "Mobile Design"],
        postedDate: "2026-04-30",
        logo: "🍕",
        featured: false,
    },
    {
        id: 6,
        title: "React.js Developer",
        company: "PhonePe",
        location: "Bangalore, Karnataka",
        type: "remote",
        category: "frontend",
        salary: "₹10-16 LPA",
        experience: "2-3 years",
        description: "Build payment interfaces and dashboards for India's largest UPI payment platform.",
        requirements: ["React.js", "JavaScript", "Redux", "CSS", "REST APIs"],
        postedDate: "2026-05-03",
        logo: "📱",
        featured: false,
    },
    {
        id: 7,
        title: "DevOps Engineer",
        company: "Meesho",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "devops",
        salary: "₹16-24 LPA",
        experience: "3-5 years",
        description: "Manage and scale cloud infrastructure for India's fastest growing social commerce platform.",
        requirements: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform"],
        postedDate: "2026-04-25",
        logo: "🛍️",
        featured: false,
    },
    {
        id: 8,
        title: "Full Stack Engineer",
        company: "Groww",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "fullstack",
        salary: "₹15-22 LPA",
        experience: "3-5 years",
        description: "Build investment and trading features for India's most trusted stock and mutual fund platform.",
        requirements: ["React.js", "Java/Node.js", "PostgreSQL", "Redis", "Microservices"],
        postedDate: "2026-05-04",
        logo: "📈",
        featured: true,
    },
    {
        id: 9,
        title: "Node.js Developer",
        company: "Dunzo",
        location: "Bangalore, Karnataka",
        type: "remote",
        category: "backend",
        salary: "₹10-15 LPA",
        experience: "2-4 years",
        description: "Build robust APIs and services for hyperlocal delivery operations across major Indian cities.",
        requirements: ["Node.js", "Express.js", "MongoDB", "Socket.io", "REST APIs"],
        postedDate: "2026-04-29",
        logo: "🚴",
        featured: false,
    },
    {
        id: 10,
        title: "Product Designer",
        company: "Slice",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "design",
        salary: "₹12-18 LPA",
        experience: "3-5 years",
        description: "Design next-generation credit card and payment experiences for India's youth-focused fintech.",
        requirements: ["Figma", "Product Thinking", "Motion Design", "User Testing", "Design Systems"],
        postedDate: "2026-05-02",
        logo: "💜",
        featured: false,
    },
    {
        id: 11,
        title: "React Native Developer",
        company: "Flipkart",
        location: "Bangalore, Karnataka",
        type: "full-time",
        category: "frontend",
        salary: "₹14-20 LPA",
        experience: "3-5 years",
        description: "Build and optimize the Flipkart mobile app used by 400 million+ registered users across India.",
        requirements: ["React Native", "JavaScript", "Redux", "Performance Optimization", "CI/CD"],
        postedDate: "2026-04-27",
        logo: "🛒",
        featured: true,
    },
    {
        id: 12,
        title: "Backend Developer",
        company: "Paytm",
        location: "Noida, UP",
        type: "full-time",
        category: "backend",
        salary: "₹12-18 LPA",
        experience: "2-4 years",
        description: "Develop payment processing systems and financial services APIs for India's leading payments company.",
        requirements: ["Java/Node.js", "MySQL", "Redis", "Kafka", "Microservices"],
        postedDate: "2026-04-26",
        logo: "💰",
        featured: false,
    },
    {
        id: 13,
        title: "Frontend Engineer",
        company: "Nykaa",
        location: "Mumbai, Maharashtra",
        type: "remote",
        category: "frontend",
        salary: "₹10-15 LPA",
        experience: "2-3 years",
        description: "Create engaging shopping experiences for India's leading beauty and fashion e-commerce platform.",
        requirements: ["React.js", "Next.js", "TypeScript", "Performance", "SEO"],
        postedDate: "2026-05-03",
        logo: "💄",
        featured: false,
    },
    {
        id: 14,
        title: "Full Stack Developer",
        company: "Urban Company",
        location: "Gurugram, Haryana",
        type: "contract",
        category: "fullstack",
        salary: "₹12-16 LPA",
        experience: "2-4 years",
        description: "Build service booking and partner management systems for India's leading home services platform.",
        requirements: ["React.js", "Node.js", "MongoDB", "Maps API", "Socket.io"],
        postedDate: "2026-04-24",
        logo: "🔧",
        featured: false,
    },
    {
        id: 15,
        title: "DevOps Engineer",
        company: "BharatPe",
        location: "Delhi",
        type: "full-time",
        category: "devops",
        salary: "₹14-20 LPA",
        experience: "3-5 years",
        description: "Build and maintain cloud infrastructure for India's leading merchant payment and lending platform.",
        requirements: ["AWS/GCP", "Docker", "Kubernetes", "Jenkins", "Monitoring"],
        postedDate: "2026-05-01",
        logo: "🇮🇳",
        featured: false,
    },
    {
        id: 16,
        title: "API Developer",
        company: "Postman",
        location: "Bangalore, Karnataka",
        type: "remote",
        category: "backend",
        salary: "₹20-30 LPA",
        experience: "4-6 years",
        description: "Build developer tools and APIs used by 30 million+ developers worldwide from Postman's India office.",
        requirements: ["Node.js", "API Design", "OpenAPI", "TypeScript", "Testing"],
        postedDate: "2026-05-05",
        logo: "📮",
        featured: true,
    },
    {
        id: 17,
        title: "UI Designer",
        company: "Juspay",
        location: "Bangalore, Karnataka",
        type: "part-time",
        category: "design",
        salary: "₹6-10 LPA",
        experience: "1-3 years",
        description: "Design checkout and payment UI components used by millions of users across major Indian platforms.",
        requirements: ["Figma", "UI Design", "Component Design", "Accessibility", "Prototyping"],
        postedDate: "2026-04-30",
        logo: "🎨",
        featured: false,
    },
    {
        id: 18,
        title: "Full Stack Engineer",
        company: "MakeMyTrip",
        location: "Gurugram, Haryana",
        type: "full-time",
        category: "fullstack",
        salary: "₹14-18 LPA",
        experience: "3-4 years",
        description: "Build travel booking features for India's leading online travel platform serving 50 million travelers.",
        requirements: ["React.js", "Node.js", "MySQL", "Redis", "AWS"],
        postedDate: "2026-04-22",
        logo: "✈️",
        featured: false,
    },
    {
        id: 19,
        title: "Backend Engineer",
        company: "Zepto",
        location: "Delhi",
        type: "contract",
        category: "backend",
        salary: "₹12-16 LPA",
        experience: "2-3 years",
        description: "Build inventory and order management APIs for Zepto's rapid expansion to new cities across India.",
        requirements: ["Node.js", "PostgreSQL", "Docker", "REST APIs", "Agile"],
        postedDate: "2026-05-04",
        logo: "📦",
        featured: false,
    },
    {
        id: 20,
        title: "DevOps + Cloud Engineer",
        company: "Razorpay",
        location: "Bangalore, Karnataka",
        type: "remote",
        category: "devops",
        salary: "₹20-28 LPA",
        experience: "4-6 years",
        description: "Scale and secure cloud infrastructure processing billions of rupees in daily payment transactions.",
        requirements: ["AWS", "Kubernetes", "Terraform", "Security", "SRE practices"],
        postedDate: "2026-05-05",
        logo: "☁️",
        featured: true,
    },
]